# Generated by Django 4.1.2 on 2022-10-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_date',
            field=models.DateField(),
        ),
    ]
